# Alembic Configuration

# path to migration scripts
script_location = .

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
#file_template = %%(year)d%%(month).2d%%(day).2d_%%(hour).2d%%(minute).2d-%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
# prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# string value is passed to the `datetime.tz.gettz()` function from the standard library
# Leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field of the migration file
# When the slug ends up being longer than this
# length, truncation is applied.
# defaults to 40
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# allow_null_revision = false

# naming convention used by the internal alembic operations to refer to constraint names.
# the default naming convention is just "_fk" for foreign key.
# With this, the constraint will be named, for example, account_input_id_fk
sqlalchemy.url =

# Logging configuration
[loggers]
keys = root,sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
